// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    $('img').bind('error', function() {
      return $(this).attr({
        src: './images/no_found.png'
      });
    });
    $('.img-box-absolute').click(function() {
      return $('.elzup-icon').attr('src', '//elzup.com/i/co' + ("0" + (Math.floor(Math.random() * 66) + 1)).slice(-2) + '.png');
    });
    $(".btn-jump").click(function() {
      var id, p;
      id = $(this).attr('for');
      p = $(id).offset().top;
      $('html,body').animate({
        scrollTop: p
      }, 'fast');
      return false;
    });
    $('[data-toggle=jumpopen]').click(function() {
      return window.open($(this).attr("data-url"));
    });
    return $('[data-toggle=jump]').click(function() {
      return window.location.href = $(this).attr("data-url");
    });
  });

}).call(this);
