// Generated by CoffeeScript 1.7.1
(function() {
  var flip_on, wait;

  $(function() {
    var STOP_TIME, setStartAnime;
    STOP_TIME = 180;
    $('.front').show();
    $('.back').hide();
    $(".cell").hover(function() {
      var $back, $front, i, id, _i, _ref;
      $(this).children('div').removeClass("off");
      $front = $(this).children('.front');
      $back = $(this).children('.back');
      $front.addClass("on");
      id = $(this).attr('data-id');
      $('.message-' + id).show();
      for (i = _i = 0, _ref = STOP_TIME / 2; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        setTimeout(function(i) {
          return $front.css('transform', "rotate(" + (i * 180 / STOP_TIME) + "deg)");
        }, i, i);
      }
      return setTimeout(function() {
        var _j, _ref1, _results;
        $front.hide();
        $back.show().addClass("on");
        _results = [];
        for (i = _j = 0, _ref1 = STOP_TIME / 2; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
          _results.push(setTimeout(function(i) {
            return $back.css('transform', "rotate(" + (i * 180 / STOP_TIME - 90) + "deg)");
          }, i, i));
        }
        return _results;
      }, STOP_TIME / 2);
    }, function() {
      var $back, $front, i, id, _i, _ref;
      $(this).children('div').removeClass("on");
      $front = $(this).children('.front');
      $back = $(this).children('.back');
      $back.addClass("off");
      id = $(this).attr('data-id');
      $('.message-' + id).hide();
      for (i = _i = 0, _ref = STOP_TIME / 2; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        setTimeout(function(i) {
          return $back.css('transform', "rotate(" + (-i * 180 / STOP_TIME) + "deg)");
        }, i, i);
      }
      return setTimeout(function() {
        var _j, _ref1, _results;
        $back.hide();
        $front.show().addClass("on");
        _results = [];
        for (i = _j = 0, _ref1 = STOP_TIME / 2; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
          _results.push(setTimeout(function(i) {
            return $front.css('transform', "rotate(" + (90 - i * 180 / STOP_TIME) + "deg)");
          }, i, i));
        }
        return _results;
      }, STOP_TIME / 2);
    });
    return setStartAnime = function(selector, addClass, starttime) {
      return setTimeout(function() {
        return $(selector).addClass(addClass);
      }, starttime);
    };
  });

  flip_on = function($front, $back, time) {
    $front.css('transform', "rotate(" + time + "deg)");
    if (time === 0) {
      $front.hide();
      $back.show().addClass("on");
      return;
    }
    return setTimeout("flip_on($front, $back, " + (time - 1) + ")", 1);
  };

  wait = function(time) {
    return $.Deferred(function(defer) {
      return setTimeout(function() {
        return defer.resolve();
      }, time);
    });
  };

}).call(this);
