// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var STOP_TIME, setStartAnime;
    STOP_TIME = 0;
    $('.front').show();
    $('.back').hide();
    $(".cell").hover(function() {
      var back, front;
      $(this).children('div').removeClass("off");
      front = $(this).children('.front');
      back = $(this).children('.back');
      front.addClass("on");
      return setTimeout(function() {
        front.hide();
        return back.show().addClass("on");
      }, STOP_TIME);
    }, function() {
      var back, front;
      $(this).children('div').removeClass("on");
      front = $(this).children('.front');
      back = $(this).children('.back');
      back.addClass("off");
      return setTimeout(function() {
        back.hide();
        return front.show().addClass("off");
      }, STOP_TIME);
    });
    return setStartAnime = function(selector, addClass, starttime) {
      return setTimeout(function() {
        return $(selector).addClass(addClass);
      }, starttime);
    };
  });

}).call(this);
